version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - JWT_SECRET_KEY=your_secret_key
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: physio_user
      POSTGRES_PASSWORD: physio_password
      POSTGRES_DB: physio_db
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true