name: CI/CD - Physiotherapy Chatbot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      FLASK_APP: app.py
      FLASK_ENV: testing
      DATABASE_URL: mysql://root:root@localhost:3306/test_db
      JWT_SECRET_KEY: test_secret_key
      TESTING: true
      PYTHONPATH: ${{ github.workspace }}/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs checkout # Download LFS files
      - name: Pull LFS files
        run: git lfs pull
      - name: Check model file
        run: ls -lh backend/models/
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-test.txt
        working-directory: ${{ github.workspace }}

      - name: Run Backend Tests
        run: |
          cd backend
          pytest --maxfail=5 --disable-warnings tests/
        working-directory: ${{ github.workspace }}

  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/frontend

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false
        working-directory: ${{ github.workspace }}/frontend
